name: effective_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.5
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  easy_localization: ^3.0.4
  go_router: ^13.1.0
  dio: ^5.4.1
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'   
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

flutter:
   uses-material-design: true
   assets:
      - assets/
      - assets/images/
      - assets/images/png/
      - assets/icons/
      - assets/icons/svg/

   fonts:
    - family: sf_pro_display
      fonts:
        - asset: fonts/sf_pro_display/SFPRODISPLAYREGULAR.OTF